### ISSUE TITLE
configs for other biomes

### ISSUE THREAD

**Issue by FatmanC** [tastybento/greenhouses#12]
asked in the discussions on spigot, without adequate information, so im now posting here to try and get some further information. 
trying to create  various other biomes, such as end, and ocean temple type one for guardians to spawn. 
this is an example of a config i tried for the end, but it is not working. 

```
End:
friendlyname: "End"
biome: End
icon: end_stone
priority: 1
contents: END_STONE:8 PURPUR_BLOCK:2
watercoverage: 0
plants:
CHORUS_TREE: 10:END_STONE
# Mobs that may spawn.
# Format:
# Entity name: % chance:Block on which the mob will spawn
mobs:
ENDERMAN: 10:END_STONE
# The minimum number of blocks each mob requires.
# Mobs will not spawn if there is more than 1 per this number of
# blocks in the greenhouse. e.g., in this case only 2 mobs will spawn if the
# greenhouse area is 18 blocks
moblimit: 3
conversions: DIRT:0:30:END_STONE:0
```

please advise what i need to fix to get an end greenhouse, and an ocean temple/second ocean type greenhouse to have guardians spawning

**Comment by tastybento** [comment]
Here's an End Biome. Note that the actual name of the End's biome is SKY. Also, capitals have to be used. For blocks, I recommend you check them out in the [Bukkit java docs](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html).

```
biomes:
  End:
    friendlyname: "End"
    biome: SKY
    icon: ENDER_STONE
    priority: 1
    contents: ENDER_STONE:8 PURPUR_BLOCK:2
    watercoverage: 0
    # Use Chorus Flower because it will grow and make chorus plant blocks
    plants:
      CHORUS_FLOWER: 10:ENDER_STONE
    # Mobs that may spawn.
    # Format:
    # Entity name: % chance:Block on which the mob will spawn
    mobs:
      ENDERMAN: 10:ENDER_STONE
    moblimit: 3
    conversions: DIRT:0:30:ENDER_STONE:0
```

Here's one for Guardians:

```
  DEEP_OCEAN:
    biome: DEEP_OCEAN
    icon: WATER_BUCKET
    priority: 8
    # Lots of water required!
    watercoverage: 95
    mobs:
      SQUID: 10:STATIONARY_WATER
      GUARDIAN: 10:STATIONARY_WATER
    moblimit: 9
```
Note that for mobs to spawn in the greenhouse, there must be 2 blocks of air above the surface of the water. Spawn-on blocks must be on the surface and not below the surface.
